[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "cctalklab"
version = "0.1.0"
description = "CCtalk development, diagnostic and bus analysis tool"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Andrei Sitnikov" }
]

[project.scripts]
cctalklab = "cctalklab.main:main"

[tool.setuptools.packages.find]
where = ["src"]